<?php

/**
 * @file
 * Contains backgrounds.page.inc.
 *
 * Page callback for Backgrounds entities.
 */

use Drupal\Core\Render\Element;
use Drupal\Core\Link;
use Drupal\Core\Url;

/**
 * Prepares variables for Backgrounds templates.
 *
 * Default template: backgrounds.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the user information and any
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_backgrounds(array &$variables) {
  // Fetch backgrounds Entity Object.
  $backgrounds = $variables['elements']['#backgrounds'];

  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
