<?php

/**
 * @file
 * Contains lifebook.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function lifebook_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the lifebook module.
    case 'help.page.lifebook':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('lifebook') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function lifebook_theme() {
  $theme = [];
  $theme['chapters'] = [
    'render element' => 'elements',
    'file' => 'chapters.page.inc',
    'template' => 'chapters',
  ];
  $theme['book'] = [
    'render element' => 'elements',
    'file' => 'book.page.inc',
    'template' => 'book',
  ];
  $theme['book_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'book.page.inc',
  ];
$theme['project'] = [
    'render element' => 'elements',
    'file' => 'project.page.inc',
    'template' => 'project',
  ];
  $theme['project_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'project.page.inc',
  ];
  $theme['page_object'] = [
    'render element' => 'elements',
    'file' => 'page_object.page.inc',
    'template' => 'page_object',
  ];
  $theme['page_object_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'page_object.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function lifebook_theme_suggestions_book(array $variables) {
  $suggestions = array();
  $entity = $variables['elements']['#book'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'book__' . $sanitized_view_mode;
  $suggestions[] = 'book__' . $entity->bundle();
  $suggestions[] = 'book__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'book__' . $entity->id();
  $suggestions[] = 'book__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}


/**
* Implements hook_theme_suggestions_HOOK().
*/
function lifebook_theme_suggestions_project(array $variables) {
  $suggestions = array();
  $entity = $variables['elements']['#project'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'project__' . $sanitized_view_mode;
  $suggestions[] = 'project__' . $entity->bundle();
  $suggestions[] = 'project__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'project__' . $entity->id();
  $suggestions[] = 'project__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}


/**
* Implements hook_theme_suggestions_HOOK().
*/
function lifebook_theme_suggestions_page_object(array $variables) {
  $suggestions = array();
  $entity = $variables['elements']['#page_object'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'page_object__' . $sanitized_view_mode;
  $suggestions[] = 'page_object__' . $entity->bundle();
  $suggestions[] = 'page_object__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'page_object__' . $entity->id();
  $suggestions[] = 'page_object__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
